# Site wide configuration

future : true
show_drafts : true
host                     : 0.0.0.0

# Site owner

owner:
  google:
    ad-client: ""
    ad-slot: ""
    analytics: ""
    verify: ""
  bing:
    verify: ""
  alexa:
    verify: ""
  yandex:
    verify: ""


# Plugin: jekyll-assets

assets:
  cache: false
