# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "default" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-GB"
title                    : "CK's Technology News"
title_separator          : "-"
name                     : "dty717"
description              : "Tech News from a strange guy!"
url                      : https://dty717.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : dty717/dty717.github.io # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : /assets/images/interface.jpg # path of fallback teaser image, e.g. "/assets/images/500x300.png"
remote_theme             : "mmistakes/minimal-mistakes"
breadcrumbs              : true #false (default)
words_per_minute         : 220
comments:
  provider               : staticman_v2 # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "/_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                : "6LcpHlwUAAAAADo0WESbO7aP8fJST1TQhKGxu2Nd"
  secret                 : "AzIUrEd+AIv8ldGHpKynLSAhGY36K6WmtfWbzrKrovUCfoOx0e4h6h/9btCage99F1RFt1RxJijR7VGlQ9uxWbd5YFTwZf7e9AgBIhEheOTU/feapBrRXgVQsjRlST4aSl7J4m888vhVHLwcas2Sar2a/byLVlb0oQU4mSaWmbY="
atom_feed:
  path                   : /atom.xml # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : algolia # lunr (default), algolia
algolia:
  application_id         : AJGNAJWQ5G # YOUR_APPLICATION_ID
  index_name             : blog	# YOUR_INDEX_NAME
  search_only_api_key    : b1b067005c6982e51974423b052c82e9 # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : false # true (default), false

# SEO Related
google_site_verification : 0ICGl54CJHd8qkF5dcwFZ4BJh3Rd32HT2juJfVKvl-U
bing_site_verification   : F2114100A03AB09E9382ACFB08C41A27
yandex_site_verification : 18edda72d035b8ee
naver_site_verification  : AAAAOtwlDIS1qZ6/S1xeS6V6XqIZqNzEcqccwYKCokspmRlm1tMOuMNfRkVJAH5TiRwP1D+ZaCUk+QYzAL0gObqMwWM=

# Social Sharing
twitter:
  username               : "CKsTechNews"
facebook:
  username               : "dty717"
  app_id                 :
  publisher              :
og_image                 : /assets/images/interface.jpg # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links:
    - "https://www.twitter.com/CKsTechNews"
    - "https://www.linkedin.com/in/ck-s-technology-news-ab7a25164/" #fixme
  #  - "https://medium.com/" #fixme
    - "https://github.com/dty717"
    - "https://www.tumblr.com/CKsTechnologyBlog"
  #  - "https://path.com/CK's Technology News" #fixme

# Analytics
analytics:
  provider               : google-universal # false (default), "google", "google-universal" or "custom"
  google:
    tracking_id          : UA-27980244-3
    anonymize_ip         : true # false (default)


# Site Author
author:
  name             : "dty717"
  avatar           : /assets/images/bio-photo.jpg # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Page...<br>under<br>construction<br>...!"
  location         : "Lausanne, Swiss"
  email            : "dty717@protonmail.com"
  uri              : # fixme
  home             : "https://dty717.github.io" # null (default), "absolute or relative url to link to author home"
  bitbucket        : dty717
  codepen          : # fixme
  dribbble         : # fixme
  flickr           : # fixme
  facebook         : CKs-Technology-News-147142349441817
  foursquare       : # fixme
  github           : dty717
  gitlab           : dty717
  google_plus      : # fixme
  keybase          : chefkoch
  instagram        : # fixme
  lastfm           : # fixme
  linkedin         : ck-s-technology-news-ab7a25164 # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  pinterest        : chefkoch0480
  soundcloud       : dty717-2
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           : # fixme
  twitter          : CKsTechNews
  vine             : # fixme
  weibo            : # fixme
  xing             : # fixme
  youtube          : "https://www.youtube.com/channel/UCTbmGi3pLfu5JFeA5ONdoQA"
  medium           : # fixme
  newsletter       : "4ea406"
  #vimeo           : falstaff # fixme
  #spotify         : nvinside99 # fixme
  #Riot.im         : "#cknews:matrix.org" # fixme
  #reddit          : CKsTechnologyNews # fixme
  #path            : 5ab32c099bcbdca1e2becbea # fixme


# Reading Files
include:
  - .htaccess
  - _pages
#  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 8 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# CDN services such as CloudFlare provide optional automatic minification for HTML, CSS, and JavaScript. If you are serving your site via such a service and have minification enabled, this configuration might be redundant.
compress_html:
  clippings: all
  ignore:
    envs: development #disable compression in dev environment


# Defaults
defaults:
  # _posts
  - scope:
      path: _posts
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: _path
      type: pages
    values:
      layout: single
      author_profile: true
